import { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export const Layout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html
            lang='ru'
            suppressHydrationWarning
            className='h-full'
        >
            <body className={inter.className + ' h-full w-full'}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    enableColorScheme
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
};
